version: '7'

networks:
  api-network:
    driver: bridge

services:

  #mysql container

  database:
    image: mysql:latest
    container_name: mysql-container

    environment:
      MYSQL_USER: davi
      MYSQL_DATABASE: database-test
      MYSQL_ROOT_PASSWORD: my-pass
      MYSQL_PASSWORD: my-pass

    volumes:
      - ./volume-mysql:/var/lib/mysql
    ports:
      - "3308:3308"
    networks:
      - api-network
    

  #api container
  api-container:
    build: .
    container_name: api-container

    depends_on:
      - database
    environment:
      DATABASE: database-test
      DATABASE_USER: root
      DATABASE_HOST: localhost
      DATABASE_PASSWORD: my-pass
      DATABASE_PORT: 3308

    ports:
      - "8000:8000"
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000

    networks:
      - api-network
